Exclude variables that exist in new environment
degica/barcelona pull request #643
Opened 2021-01-06 07:53 UTC by k2nr

Consider the following case:

- non-secret env var `VARIABLE` exists as a legacy `EnvVar`
- secret environment `VARIABLE` exists in `environment`

With this case Barcelona adds `VARIABLE` to both `Environment` and `Secrets` of task definition.

This PR solves the above issue by removing legacy environment variables that also exist in `environment`

2021-01-06 08:03 UTC, davidsiaw requested changes
Can we write a test that fails with the old code?

2021-01-06 08:06 UTC, k2nr commented
sure

2021-01-06 08:21 UTC, k2nr commented
Done. confirmed that the spec fails without the fix

2021-01-06 11:02 UTC, k2nr commented
OK this is ready for review

2021-01-06 11:05 UTC, degicat commented
@davidsiaw please review this

2021-01-07 10:01 UTC, davidsiaw requested changes
Just a few small changes for readability

2021-01-08 09:27 UTC, k2nr commented
Thanks for the suggestions! I picked your suggestions.

2021-01-15 07:07 UTC, davidsiaw approved these changes
LGTM

2021-01-15 07:07 UTC, merged