Enable container metadata for ECS
degica/barcelona pull request #801
Opened 2023-10-31 07:01 UTC by showwin

## Context
We are setting up ddagent as daemon service on ECS. The hats containers need to know the EC2 host private IP address to communicate with the service-daemon ddagent, [ref](https://docs.datadoghq.com/containers/amazon_ecs/apm/?tab=ecscontainermetadatafile#:~:text=cat%20%24ECS_CONTAINER_METADATA_FILE%20%7C%20jq%20%2Dr%20.HostPrivateIPv4Address).
The container can get the IP address by `cat $ECS_CONTAINER_METADATA_FILE | jq -r .HostPrivateIPv4Address` as explained in the above document, but this environment variable is blank by default. We need to turn on the container metadata by defining `ECS_ENABLE_CONTAINER_METADATA=true` in ECS config, [ref](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-metadata.html#:~:text=ECS_ENABLE_CONTAINER_METADATA%3Dtrue).

## Steps after merging this PR
1. `bcn district apply staging`
1. Go to CF page on console and apply changes
1. Use [Instance Refresh](https://docs.aws.amazon.com/autoscaling/ec2/userguide/start-instance-refresh.html) feature with 90% minimum healthy instance to replace existing servers.

2023-10-31 07:12 UTC, degikko commented
@davidsiaw can you help us review this PR, please?

2023-10-31 08:13 UTC, davidsiaw commented
I had a quick look and wondered why we didn't do this but came across this. I am not sure if this is something we want to depend on?

<img width="457" alt="スクリーンショット 2023-10-31 17 12 46" src="https://github.com/degica/barcelona/assets/874280/4bbcb77a-3531-487a-ae6b-2afda6d77c35">

2023-10-31 08:22 UTC, showwin commented
When we move to Fargate, we cannot use daemon service for ddagent. So, we will change the architecture to use side-car model.
<img width="1157" alt="Screenshot 2023-10-31 at 17 21 44" src="https://github.com/degica/barcelona/assets/1732016/81a3d94a-45ac-45a9-90bf-09cb4814bfd0">
link: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_services.html

I guess we can start using the side-car model from now on, but I don't know the background of the current decision well since Franka helped this project for core-team before.
As far as I can guess, the daemon service is a bit cost-efficient compared to side-car.

2023-11-01 03:08 UTC, davidsiaw requested changes
@showwin how are you adding ECS daemon? are you doing it through a plugin?

2023-11-01 03:58 UTC, showwin commented
@davidsiaw It's by Terraform and this is the PR, https://github.com/degica/terraform-modules/pull/40.

2023-11-01 04:27 UTC, davidsiaw approved these changes
LGTM then. you will need to ensure that this is in  sync with whatever updates you make to that in the future.

2023-11-01 04:27 UTC, merged

2023-11-22 06:10 UTC, showwin commented
Just a note in the future: 
I needed to execute `bcn district apply <district>` command to upload the ECS config file to S3. (but you won't see any changes on the change set in CloudFormation)